### ISSUE TITLE
Headless (CLI) e107 tries to use uninitialized SQL if siteurl preference is not cached

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#3033]
# Problem

If `e107_system/*/cache/content/S_Config_core.cache.php` exists and contains `siteurl`, headless e107 can skip the database for getting the website URL and continue initializing until the database actually loads.

Without the cache, this happens:

```php
deltik@host1 [~/public_html]$ /opt/cpanel/ea-php72/root/usr/bin/php -d allow_url_fopen=On -d display_errors=On cron.php
deltik@host1 [~/public_html]$ rm -fv e107_system/6de9d0d30a/cache/content/S_Config_core.cache.php
removed ‘e107_system/6de9d0d30a/cache/content/S_Config_core.cache.php’
deltik@host1 [~/public_html]$ /opt/cpanel/ea-php72/root/usr/bin/php -d allow_url_fopen=On -d display_errors=On cron.php

Fatal error: Uncaught Error: Call to a member function query() on null in /home/deltik/public_html/e107_handlers/mysql_class.php:535
Stack trace:
#0 /home/deltik/public_html/e107_handlers/mysql_class.php(803): e_db_mysql->db_Query('SELECT e107_val...', NULL, 'db_Select', false, '', '')
#1 /home/deltik/public_html/e107_handlers/pref_class.php(479): e_db_mysql->select('core', 'e107_value', 'e107_name='Site...')
#2 /home/deltik/public_html/e107_handlers/pref_class.php(450): e_pref->_load(false)
#3 /home/deltik/public_html/e107_handlers/pref_class.php(848): e_pref->load()
#4 /home/deltik/public_html/e107_handlers/e107_class.php(1009): e_core_pref->__construct('core', true)
#5 /home/deltik/public_html/e107_handlers/e107_class.php(1032): e107::getConfig()
#6 /home/deltik/public_html/e107_handlers/e107_class.php(4479): e107::getPref('siteurl')
#7 /home/deltik/public_html/e107_handlers/e107_class.php(413): e107->set_urls()
#8 /home/deltik/public_html/e107_handlers/e107_class.php(317): e107->_init(Array, '/home/deltik/pu...', Arra in /home/deltik/public_html/e107_handlers/mysql_class.php on line 535
```

Headless e107 cannot be used in this case.

**Comment by Deltik** [comment]
Caused by f7eadfd588
