### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/domain.com/e107_handlers/e_db_pdo_class.php:224

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#3907]
```
2019/07/28 19:55:08 [error] 20844#20844: *12918731 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/domain.com/e107_handlers/e_db_pdo_class.php:224
Stack trace:
#0 /var/www/domain.com/e107_handlers/e_db_pdo_class.php(2799): e_db_pdo->database(NULL)
#1 /var/www/domain.com/e107_handlers/e_db_pdo_class.php(1945): e_db_pdo->_getMySQLaccess()
#2 /var/www/domain.com/e107_handlers/userclass_class.php(160): e_db_pdo->field('userclass_class...', 'userclass_paren...')
#3 /var/www/domain.com/e107_handlers/userclass_class.php(94): user_class->readTree(true)
#4 /var/www/domain.com/e107_handlers/e107_class.php(945): user_class->__construct(NULL)
#5 /var/www/domain.com/e107_handlers/e107_class.php(1721): e107::getSingleton('user_class', '../handlers/use...')
#6 /var/www/domain.com/e107_handlers/e107_class.php(5100): e107::getUserClass()
#7 /var/www/domain.com/class2.php(1711): e107->__get('user_class')
#8 /var/www/domain.com/add/index.php(13): check_class('Uploader')
#9" while reading upstream, client: 104.174.206.178, server: www.domain.com, request: "GET /add/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.domain.com", referrer: "https://www.domain.com/add/"
```

**Comment by Moc** [comment]
When exactly does this happen? I can see it is related to the userclass page, but do you click something specifically?

**Comment by mostym** [comment]
I created a custom page called /add

**Comment by mostym** [comment]
Removing the following makes the page load.  However, this is not the desired result.  I need this logic to only allow a specific user class access to this page.  Any help would be appreciated.  Thanks!

```
if (!check_class('Uploader')) {
    header('location: https://www.domain.com/');
    exit;
}
````
