### ISSUE TITLE
Uncaught Error: Call to a member function breadcrumb() on null in /var/www/domain.com/e107_plugins/download/handlers/download_class.php:576

### ISSUE THREAD

**Issue by mostym** [e107inc/e107#3909]
```
2019/07/29 08:10:09 [error] 20844#20844: *12957149 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function breadcrumb() on null in /var/www/domain.com/e107_plugins/download/handlers/download_class.php:576
Stack trace:
#0 /var/www/domain.com/e107_plugins/download/handlers/download_class.php(221): download->renderView()
#1 /var/www/domain.com/e107_plugins/download/download.php(109): download->render()
#2 /var/www/domain.com/index.php(69): include_once('/var/www/doma...')
#3 {main}
  thrown in /var/www/domain.com/e107_plugins/download/handlers/download_class.php on line 576" while reading response header from upstream, client: 40.77.167.162, server: www.domain.com, request: "GET /download/96441/fate_extella_link_update_v1-0-1_nsw-suxxors HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.domain.com"
```

**Comment by Jimmi08** [comment]
Do you use github version? Latest?

**Comment by mostym** [comment]
Yes and Yes.

**Comment by Jimmi08** [comment]
Confirmed.

**Comment by Jimmi08** [comment]
@Moc 
this issue is related to theme changes.

there is code:
```
		$sc = $this->sc;
		$sc->breadcrumb();

		// @see: #3056 fixes fatal error in case $sc is empty (what happens, if no record was found)
		$count = empty($sc) ? 0 : $sc->getVars();
```
$sc->breadcrumb(); was added without testing if $sc is empty or not like on lines bellow. 

it is this commit:
https://github.com/e107inc/e107/commit/1d311ff543f4ee0ea614386bb7e290a5557c61a2

maybe there should be just test if it's empty or instead of $sc use $this.

**Comment by CaMer0n** [comment]
@mostym @Jimmi08 Please test and re-open if necessary. Thanks.
