### ISSUE TITLE
alt_auth plugin and fatal error with php 7.2 + FIX

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3981]
With using other db option you get Fatal error because used 
mysql_real_escape_string  
function.

`Fatal error: Uncaught Error: Call to undefined function mysql_real_escape_string() in ***\e107_plugins\alt_auth\alt_auth_login_class.php:106 Stack trace: #0 ***\e107_handlers\login.php(134): alt_login->__construct('otherdb', 'xxx', 'xxx') #1 ***\e107_handlers\user_model.php(1593): userlogin->login('xxx', 'xxx', 0, '', false) #2 ***\class2.php(1278): e_user->login('xxx', 'xxx', NULL, '', false) #3 ***\login.php(13): require_once('G:\\php72\\htdocs...') #4 {main} thrown in ***\e107_plugins\alt_auth\alt_auth_login_class.php on line 106`

**Comment by Jimmi08** [comment]
This was fix, not sure if correct:
`$username = e107::getParser()->toDB($username);`
