### ISSUE TITLE
php 7.3 news_title shortcode issue

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4035]
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function news_shortcodes::sc_newstitle(), 0 passed in C:\xampp\htdocs\e107_desire\e107_core\shortcodes\batch\news_shortcodes.php on line 81 and exactly 1 expected in ***e107_core\shortcodes\batch\news_shortcodes.php:56 Stack trace: #0 ***e107_core\shortcodes\batch\news_shortcodes.php(81): news_shortcodes->sc_newstitle() #1 ***e107_handlers\shortcode_handler.php(1105): news_shortcodes->sc_newsurltitle(Array, '') #2 [internal function]: e_parse_shortcode->doCode(Array) #3 ***e107_handlers\shortcode_handler.php(972): preg_replace_callback('#\\{([A-Z][^\\x02...', Array, '\r\n ...') #4 ***e107_handlers\e_parse_class.php(880): e_parse_shortcode->parseCodes('\r\n ...', true, Object(news_shortcodes), NULL) #5 ***e107_handlers\news_class.php(407): e_parse->parseTemplate('\r\n ...', true in ***e107_core\shortcodes\batch\news_shortcodes.php on line 56`

This: 

`function sc_newstitle($parm)`

$parm doesn't have default value.

**Comment by Jimmi08** [comment]
It happens with 7.2  but only with shortcode {NEWSURLTITLE}

I switched to 7.2 and it was still there, but other themes worked... 

{NEWS_TITLE} works.
