### ISSUE TITLE
social login with FB - avoid fatal error if ID is missing

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4192]
## Motivation
Avoid fatal error if there is a setting mistake

## FR: 
add test before or don't allow activate it without ID

`Fatal error: Uncaught Hybridauth\Exception\InvalidApplicationCredentialsException: Your application id is required in order to connect to Facebook`

**Comment by tgtje** [comment]
adding : this is not for FB alone..others give same message

**Comment by Deltik** [comment]
Note to self: Stack trace:

```
[Sun Dec 26 21:57:56.544521 2021] [php:error] [pid 11279] [client 10.64.229.1:42762] PHP Fatal error:  Uncaught Hybridauth\\Exception\\InvalidApplicationCredentialsException: Your application id is required in order to connect to Facebook in /var/www/html/e107/e107_handlers/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php:253
Stack trace:
#0 /var/www/html/e107/e107_handlers/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php(109): Hybridauth\\Adapter\\OAuth2->configure()
#1 /var/www/html/e107/e107_handlers/vendor/hybridauth/hybridauth/src/Hybridauth.php(141): Hybridauth\\Adapter\\AbstractAdapter->__construct()
#2 /var/www/html/e107/e107_handlers/vendor/hybridauth/hybridauth/src/Hybridauth.php(192): Hybridauth\\Hybridauth->getAdapter()
#3 /var/www/html/e107/e107_handlers/user_handler.php(1159): Hybridauth\\Hybridauth->isConnectedWith()
#4 /var/www/html/e107/e107_handlers/e107_class.php(1186): e_user_provider->__construct()
#5 /var/www/html/e107/e107_handlers/e107_class.php(1996): e107::getObject()
#6 /var/www/html/e107/e107_core/shortcodes/batch/signup_shortcodes.php(150): e107::getUserProvider()
#7 /var/www/html/e107/e107_core/shortcodes/batch/signup_shortcodes.php(85): signup_shortcodes->generateXupLoginButtons()
#8 /var/www/html/e107/e107_plugins/social/e_shortcode.php(204): signup_shortcodes->sc_signup_xup_login()
#9 /var/www/html/e107/e107_handlers/shortcode_handler.php(275): social_shortcodes->sc_social_login()
#10 /var/www/html/e107/e107_handlers/shortcode_handler.php(1214): e_parse_shortcode->callScFuncA()
#11 [internal function]: e_parse_shortcode->doCode()
#12 /var/www/html/e107/e107_handlers/shortcode_handler.php(995): preg_replace_callback()
#13 /var/www/html/e107/e107_handlers/e_parse_class.php(824): e_parse_shortcode->parseCodes()
#14 /var/www/html/e107/e107_themes/bootstrap3/theme_shortcodes.php(236): e_parse->parseTemplate()
#15 /var/www/html/e107/e107_handlers/shortcode_handler.php(1129): theme_shortcodes->sc_bootstrap_usernav()
#16 [internal function]: e_parse_shortcode->doCode()
#17 /var/www/html/e107/e107_handlers/shortcode_handler.php(995): preg_replace_callback()
#18 /var/www/html/e107/e107_handlers/e_parse_class.php(824): e_parse_shortcode->parseCodes()
#19 /var/www/html/e107/e107_handlers/e107_class.php(373): e_parse->parseTemplate()
#20 /var/www/html/e107/e107_core/templates/header_default.php(829): e107::renderLayout()
#21 /var/www/html/e107/index.php(189): include_once('...')
#22 {main}
  thrown in /var/www/html/e107/e107_handlers/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php on line 253, referer: http://10.64.229.116/e107/
```
