### ISSUE TITLE
Undefined constant "LAN_PLUGIN_NEWS_NAME" despite #4404

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4442]
## Bug Description
```
PHP Fatal error:  Uncaught Error: Undefined constant "LAN_PLUGIN_NEWS_NAME" in /home/deltik/public_html/e107_plugins/news/news.php:86
Stack trace:
#0 /home/deltik/public_html/e107_plugins/news/news.php(75): news_front->setBreadcrumb()
#1 /home/deltik/public_html/e107_plugins/news/news.php(1890): news_front->__construct()
#2 /home/deltik/public_html/news.php(23): require_once('...')
#3 /home/deltik/public_html/index.php(107): include('...')
#4 {main}
  thrown in /home/deltik/public_html/e107_plugins/news/news.php on line 86
```

Regression was introduced in ba6344bb281c0c8562871cc8a3569ae3015543a3 as a fix for #4404:

```
deltik@host1:~/public_html$ git bisect bad     
ba6344bb281c0c8562871cc8a3569ae3015543a3 is the first bad commit
commit ba6344bb281c0c8562871cc8a3569ae3015543a3
Author: Cameron <e107inc@gmail.com>
Date:   Tue Feb 16 09:23:41 2021 -0800

    Removed deprecated PAGE_NAME from News.

 e107_languages/English/lan_news.php | 5 +----
 e107_plugins/news/news.php          | 6 +++---
 2 files changed, 4 insertions(+), 7 deletions(-)
```

`git bisect log`:
```
git bisect start
# bad: [9c9dcb5e5207aa87703da46cd7d32433513c7a65] Issue #4437 Parsing page with password.
git bisect bad 9c9dcb5e5207aa87703da46cd7d32433513c7a65
# bad: [9c9dcb5e5207aa87703da46cd7d32433513c7a65] Issue #4437 Parsing page with password.
git bisect bad 9c9dcb5e5207aa87703da46cd7d32433513c7a65
# bad: [821f2e9c222b9650c0acbe6c1359afaa4c4eeee5] Moved e_layout to menumanager_class.php
git bisect bad 821f2e9c222b9650c0acbe6c1359afaa4c4eeee5
# good: [5b9ecd22008ae52f9a3f9e5bac2677c48f83f39f] Issue #4372 Extra fields.
git bisect good 5b9ecd22008ae52f9a3f9e5bac2677c48f83f39f
# bad: [2f08384dcb61c28b6ff9bb8e291a82afbf5101d5] Issue #4400 Added test for hasMessage(false);
git bisect bad 2f08384dcb61c28b6ff9bb8e291a82afbf5101d5
# bad: [364f41231aa53532ef92d0f87dafc2a3af9666f5] #4393 Available chapter id on chapter page
git bisect bad 364f41231aa53532ef92d0f87dafc2a3af9666f5
# bad: [4203bdb2c5b5e234fa22cad8d339aaabf4562800] Removed last references to deprecated e107::getAdminLog() method.
git bisect bad 4203bdb2c5b5e234fa22cad8d339aaabf4562800
# bad: [ab546c5aab24e572d5e3a59f401008b6c7007b89] Fix for tips appearing when hovering on labels. Menu-manager selector styling on light theme.
git bisect bad ab546c5aab24e572d5e3a59f401008b6c7007b89
# bad: [ba6344bb281c0c8562871cc8a3569ae3015543a3] Removed deprecated PAGE_NAME from News.
git bisect bad ba6344bb281c0c8562871cc8a3569ae3015543a3
# first bad commit: [ba6344bb281c0c8562871cc8a3569ae3015543a3] Removed deprecated PAGE_NAME from News.
```

## How to Reproduce
I don't know.  I use the `news` plugin, though.

## Expected Behavior
No blank page when loading `/news.php`

## Screenshots
Just a blank page

### PHP Operating System

```
Linux host1.xenfinity.com 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64
```

### PHP Version

```
PHP Version 8.0.2
```

### PHP Modules

```
amqp
apcu
ast
bcmath
bz2
calendar
cgi-fcgi
Core
ctype
curl
date
dba
dom
ds
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libsmbclient
libxml
mailparse
mbstring
memcached
msgpack
mysqli
mysqlnd
OAuth
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
psr
raphf
readline
redis
Reflection
rrd
session
shmop
SimpleXML
smbclient
snmp
soap
sockets
sodium
solr
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
uuid
xdebug
xhprof
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib
zmq
```

### Client Information

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0

**Comment by CaMer0n** [comment]
@Deltik Please scan your plugin directories.

**Comment by Deltik** [comment]
Sure enough, that fixed the problem.  How would a regular admin know to do this once they upgrade to the upcoming stable version of e107?

**Comment by CaMer0n** [comment]
@Deltik This should fix it.

**Comment by Deltik** [comment]
[Fix](https://github.com/e107inc/e107/commit/fb3888abc3ee7b196a93d0916e0d0de23bf33b4e) verified.  Thank you, @CaMer0n!
