### ISSUE TITLE
PHP 8 fatal error in `e_signup::renderResendForm()`

### ISSUE THREAD

**Issue by Deltik** [e107inc/e107#4493]
## Bug Description
```
PHP Fatal error:  Uncaught Error: Undefined constant "USER_WIDTH" in /home/deltik/public_html/e107_handlers/e_signup_class.php:247
Stack trace:
#0 /home/deltik/public_html/e107_handlers/e_signup_class.php(79): e_signup->renderResendForm()
#1 /home/deltik/public_html/signup.php(172): e_signup->run()
#2 {main}
  thrown in /home/deltik/public_html/e107_handlers/e_signup_class.php on line 247
```

## How to Reproduce
1. Make sure registrations are enabled in `/e107_admin/prefs.php#nav-core-prefs-registration` » User registration system.
2. Go to `/signup.php?resend`.

## Expected Behavior
Probably some form showing up instead of an incompletely rendered page

**Comment by Deltik** [comment]
https://github.com/e107inc/e107/commit/c57b029877b3d8c45445439e2ade9f044da6c0fe fix verified
