### ISSUE TITLE
Rare fatal error with social login and Logged-in-as functionality 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4598]
## Motivation
I got fatal error, but because this is special situation, I don't take it as bug, but it will be nice to improve the code.

- user list was imported from another source because testing purposes. They signed up with some provider, probably steam. 
- main admin was log in on some user behalf (via administration of users)
- when they tried to log off on frontend, this happened:

` Fatal error: Uncaught Hybridauth\Exception\InvalidArgumentException: Unknown Provider. in C:\xampp74\htdocs****e107_handlers\vendor\hybridauth\hybridauth\src\Hybridauth.php:161 Stack trace: #0 C:\xampp74\htdocs****e107_handlers\vendor\hybridauth\hybridauth\src\Hybridauth.php(119): Hybridauth\Hybridauth->getProviderConfig('steam') #1 C:\xampp74\htdocs****e107_handlers\vendor\hybridauth\hybridauth\src\Hybridauth.php(192): Hybridauth\Hybridauth->getAdapter('Steam') #2 C:\xampp74\htdocs****e107_handlers\user_handler.php(1159): Hybridauth\Hybridauth->isConnectedWith('Steam') #3 C:\xampp74\htdocs****e107_handlers\e107_class.php(1186): e_user_provider->__construct('Steam') #4 C:\xampp74\htdocs****e107_handlers\e107_class.php(1996): e107::getObject('e_user_provider', 'Steam') #5 C:\xampp74\htdocs****e107_handlers\user_model.php(1737): e107::getUserProvider('Steam') #6 C:\xampp74\htdocs****e107_handlers\user_model.php(1749): e_user->initProvider() #7 C:\xampp7 in C:\xampp74\htdocs****e107_handlers\vendor\hybridauth\hybridauth\src\Hybridauth.php on line 161`

**Comment by Jimmi08** [comment]
This was fixed with this commit.
+ plus social plugin update is needed


https://github.com/Deltik/e107/commit/14372cdaff3919467d708127f597d00bea21fe43
