### ISSUE TITLE
Fatal error when deleting logs 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4830]
## Bug Description

```
Fatal error: Uncaught Error: Object of class PDOStatement could not be converted to string in C:\xampp\htdocs\e107-2_3_3_git\e107_admin\admin_log.php:406
Stack trace:
 #0 C:\xampp\htdocs\e107-2_3_3_git\e107_admin\admin_log.php(276): admin_log_ui->maintenanceProcess()
 #1 C:\xampp\htdocs\e107-2_3_3_git\e107_handlers\admin_ui.php(2354): admin_log_ui->maintenancePage()
 #2 C:\xampp\htdocs\e107-2_3_3_git\e107_handlers\admin_ui.php(1375): e_admin_controller->dispatchPage()
 #3 C:\xampp\htdocs\e107-2_3_3_git\e107_admin\admin_log.php(864): e_admin_dispatcher->runPage()
 #4 {main} thrown in C:\xampp\htdocs\e107-2_3_3_git\e107_admin\admin_log.php on line 406
```

## How to Reproduce
1. Go to Logs
2. Click on Options
3. Click on Delete old entries (any button)

## Screenshots
![image](https://user-images.githubusercontent.com/5429548/181620178-d98474c2-b035-4539-a01e-32027790388b.png)

### PHP Operating System

```
Windows NT LAPTOP-C59ADQ1N 10.0 build 19044 (Windows 10) AMD64
```

### PHP Version

```
PHP  8.1.4 
```

**Comment by tgtje** [comment]
Just **confirmation** php 8.1.6  2.3.3  Win 11 Xampp
