### ISSUE TITLE
forum_viewforum.php only displays {---CAPTION---} and {---BREADCRUMS---} 

### ISSUE THREAD

**Issue by STR82UII** [e107inc/e107#4852]
## Bug Description
forum_viewforum.php only displays {---CAPTION---} and {---BREADCRUMS---} on this page. My forum is here https://www.emailtoinmates.com/forum  and if you click one of the topic/forum links it will show you what it's doing. (or not doing as it were).

The veiwtopic.php page displays the individual topics properly but those pages can't be reached because  of the error.(https://www.emailtoinmates.com/extras/forum/forum_viewtopic.php?id=19)

Upgraded from a v .7 site a month ago and it's done it since, original was working properly.
Server has PHP 7.4\72

**Comment by STR82UII** [comment]
Forgot to mention, the meta title tags of the blank pages is correct, the page's title shows in the tab etc

**Comment by Jimmi08** [comment]
@STR82UII check your error logs.  This look `({---CAPTION---} and {---BREADCRUMS---}) ` is when there is fatal error on the page. 

And you should switch to SEF-URLs for forum, if you can.

**Comment by STR82UII** [comment]
**From Error_log after clicking all sections/forums:**

text/x-generic error_log ( ASCII text )
[18-Aug-2022 19:05:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479
[18-Aug-2022 19:05:50 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479
[18-Aug-2022 19:05:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479
[18-Aug-2022 19:05:55 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479
[18-Aug-2022 19:05:58 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479
[18-Aug-2022 19:06:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function setVars() on null in /home2/emailnam/public_html/extras/forum/forum_viewforum.php:479
Stack trace:
#0 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(421): forum_viewforum_front->parse_thread(Array)
#1 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(56): forum_viewforum_front->init()
#2 /home2/emailnam/public_html/extras/forum/forum_viewforum.php(565): forum_viewforum_front->__construct()
#3 {main}
  thrown in /home2/emailnam/public_html/extras/forum/forum_viewforum.php on line 479

**Comment by Jimmi08** [comment]
@STR82UII what version of e107 are you using?  Maybe it was fixed because I tried it with latest version of forum plugin and no issue with legacy urls.  It would be nice to have your forum data, can you catch me on gitter? I would like to help you (if I am able) because I run 2 big forums and I want to have something like this fixed. Lately there was some fixes of subforum. But with your data I am able to test it with latest e107 version.

Ad SEF-URL, you should see something like this:
![image](https://user-images.githubusercontent.com/5429548/185482715-a0c23d9f-1a54-4bd1-b304-daa03b6d60f6.png)

Do you know how to export e107 Data?   Database/Tools/Export - and select forum tables and forum prefs.

**Comment by STR82UII** [comment]
That URL configuration is on/activated as shown in your post. I turned it off to test and get the same error.

The site was recently updated/upgraded to V2.3.2

In "tools/Database", the only option is to backup site data, backup. If you can give me your email address, I can give you admin privileges

**Comment by STR82UII** [comment]
Here is what I got

**Comment by Jimmi08** [comment]
You should be part of https://gitter.im/e107inc/e107  it is the quickest way  how to get help and a way how to do private chat

jimako@e107sk.com

**Comment by Jimmi08** [comment]
> In "tools/Database", the only option is to backup site data, backup. If you can give me your email address, I can give you admin privileges

![image](https://user-images.githubusercontent.com/5429548/185489873-0fb3758a-ae56-4f46-905f-93c5ab3841bd.png)

**Comment by STR82UII** [comment]
OK, this is from the "Export Site Data"

**Comment by STR82UII** [comment]
[e107Export_2022-08-18a.zip](https://github.com/e107inc/e107/files/9377492/e107Export_2022-08-18a.zip)

Sorry for the blank file, this is correct

**Comment by STR82UII** [comment]
Glitter wants me to use "Matrix" but I'm using windows 10 in S mode so it won't install.

I just created a main admin account for you at https://www.emailtoinmates.com/

**Comment by STR82UII** [comment]
Did you get the email with your password?

**Comment by Jimmi08** [comment]
> Glitter wants me to use "Matrix" but I'm using windows 10 in S mode so it won't install.
> 
> I just created a main admin account for you at https://www.emailtoinmates.com/

Weird, I am logged it with github account, Win 10 too.  Email came. At first your data

**Comment by STR82UII** [comment]
Mine is Windows 10 In S Mode, it only allows installing Microsoft Store apps

**Comment by Jimmi08** [comment]
This doesn't fix your problem but why you was getting legacy urls: 
Your forums didn't have SEF-URL versions. You didn't know this before displaying this field. 

![image](https://user-images.githubusercontent.com/5429548/185493664-db7886be-c392-4e68-a0fd-40c07328fe7a.png)

**Comment by Jimmi08** [comment]
With latest 2.3.3 git it works correctly. 
You could update forum plugin (only this one) from github version 2.3.3 
![image](https://user-images.githubusercontent.com/5429548/185494399-4406b590-8c46-469e-9c30-acfedc00d16a.png)

**Comment by STR82UII** [comment]
Understood, I'll try to get that....

**Comment by Moc** [comment]
@STR82UII Does the issue still occur using the latest files from Github?
