### ISSUE TITLE
[Feature request]: PHP 8.3 Compatibility

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107#5114]
### Motivation

Needed

### Proposed Solution

Rework code where necessary. 

### Alternatives

none

**Comment by PH5HP** [comment]
Hi Cameron,

It still does not work with PHP 8.3. I still have the error 500 and I can see some errors in the PHP log:

[28-Nov-2025 23:38:25 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Override::__construct() expects exactly 0 arguments, 1 given in /var/www/users/user-30/html-2/web/e107_handlers/e107_class.php:1153
Stack trace:
#0 /var/www/users/user-30/html-2/web/e107_handlers/e107_class.php(1153): Override->__construct()
#1 /var/www/users/user-30/html-2/web/class2.php(643): e107::getSingleton()
#2 /var/www/users/user-30/html-2/web/news.php(22): require_once('/var/www/users/...')
#3 {main}
  thrown in /var/www/users/user-30/html-2/web/e107_handlers/e107_class.php on line 1153


Kind regards,
Henk

**Comment by Deltik** [comment]
@PH5HP: Indeed, that is a plugin issue.  I did consider writing a transpiler, possibly with [Rector](https://github.com/rectorphp/rector), to upgrade old plugins to be compatible automatically, but this would be a substantial amount of work.

Basically, one would have to go through all the code and wrap undefined constants with `defset('…')`.  ([Example](https://github.com/e107inc/e107/commit/0a1150e860447865eae6956f570a910f93f65c0b#diff-06b8c56ba481420ad3059bc7f78a448f7f029edd40e15c7a7a2c63fd6aeb0e9aL335))

So `GB_LAN_SIGN` would become `defset('GB_LAN_SIGN')` and so on.

**Comment by PH5HP** [comment]
Hi,

Thank you for helping me. So this would become:
define(GB_LAN_SIGN,"Sign Guestbook");

changed to:
defset(GB_LAN_SIGN,"Sign Guestbook");

Kind regards,
Henk

**Comment by PH5HP** [comment]
Hi,

Ah. No idea how that works :-) ...

Kind regards,
Henk

**Comment by Jimmi08** [comment]
> You can always try [@Jimmi08](https://github.com/Jimmi08) version.... https://github.com/Jimako-e107-plugins/e107-old-plugins/tree/master/guestbook

It is backup for PHP 5 / 7,  it is not my version
